name: 'olist_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'olist_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# These settings can be overridden in the individual model files using the `{{ config(...) }}` macro.
models:
  olist_analytics:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold