table 'gold fct_order_items'
	lineageTag: 43a75220-fffd-47bc-92ec-f781aed42f6a

	column order_id
		dataType: string
		lineageTag: 26e1d35d-71fd-4a04-8f52-b264eaea25c6
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: 0dc57a1c-1358-4049-9802-d657d880e945
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 1d0c5443-55c2-4064-8817-a9572a3f891f
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 6dfdb8f8-0a6d-4fea-a2b0-7bfff6bf7621
		summarizeBy: none
		sourceColumn: seller_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 77becaf2-b80e-4780-9cc9-665a2e0666a0
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 5d4bf6fb-2676-4a1a-bfc7-4b8f668d2d16
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ae53951-b3e3-41d6-bb75-0c9b0017ad14
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 0663c45e-2f69-4e2f-8a8a-c88192962698
		summarizeBy: none
		sourceColumn: order_approved_at

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0ec3be8b-fc07-466a-a957-2d8f27894f31
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 23728355-7c12-43af-8a2d-f66010de8dd2
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1fa4a4ac-63cd-4160-8375-30147bbefb50
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 87619a11-31f2-4cdd-b701-952769101cbd
		summarizeBy: none
		sourceColumn: shipping_limit_date

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 0b5ae223-8648-4a1c-8def-3e68a77cd8fc
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value
		dataType: double
		lineageTag: 5c2523df-5f04-46de-911b-fbf7e1da13ef
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rate
		dataType: double
		lineageTag: 6d626a3b-17fd-4e5a-8bec-f7f01a4d0921
		summarizeBy: sum
		sourceColumn: rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price_eur
		dataType: double
		lineageTag: b642d865-2860-413f-a9e1-547ce22cd529
		summarizeBy: sum
		sourceColumn: price_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value_eur
		dataType: double
		lineageTag: ef28ed49-c85f-4e47-8924-3665fbda5204
		summarizeBy: sum
		sourceColumn: freight_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_category_name
		dataType: string
		isHidden
		lineageTag: 40957334-5205-402f-addb-c5dccf22e011
		summarizeBy: none
		sourceColumn: product_category_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_category_name_english
		dataType: string
		isHidden
		lineageTag: 09538019-6e98-4541-a945-552b286f1f75
		summarizeBy: none
		sourceColumn: product_category_name_english

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: double
		isHidden
		lineageTag: 7d8c0509-d463-41ea-b280-81e59fc52a7d
		summarizeBy: sum
		sourceColumn: product_weight_g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column seller_zip_code_prefix
		dataType: string
		isHidden
		lineageTag: eaaaa815-7f08-4cdf-9b46-99f0f49b4c7c
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column seller_lat
		dataType: double
		isHidden
		lineageTag: 974e69f7-75bb-4b88-9f30-eeafde32bf85
		summarizeBy: sum
		sourceColumn: seller_lat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column seller_lng
		dataType: double
		isHidden
		lineageTag: 219c36ec-07f2-471d-a019-8e1635955660
		summarizeBy: sum
		sourceColumn: seller_lng

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column seller_city
		dataType: string
		isHidden
		lineageTag: 092fda09-f529-4a50-afc0-5b2eaf66bc03
		summarizeBy: none
		sourceColumn: seller_city

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		isHidden
		lineageTag: ef2ce850-ea05-4ad8-a4b3-c0b67d49fc19
		summarizeBy: none
		sourceColumn: seller_state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		isHidden
		lineageTag: db8fc12c-c3ce-4a56-afa3-761b9b86bd7d
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_lat
		dataType: double
		isHidden
		lineageTag: 5ee05415-9695-4fde-8e5f-6c503fd6844a
		summarizeBy: sum
		sourceColumn: customer_lat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_lng
		dataType: double
		isHidden
		lineageTag: 98b0d2b3-ed02-447a-b5cd-7d5da675f98d
		summarizeBy: sum
		sourceColumn: customer_lng

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_city
		dataType: string
		isHidden
		lineageTag: eade67cf-3453-4f27-82e0-d3434b0aabf9
		summarizeBy: none
		sourceColumn: customer_city

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		isHidden
		lineageTag: 825a8edf-a51b-482d-ac69-417af39761ee
		summarizeBy: none
		sourceColumn: customer_state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 614657e9-b7e7-4d68-93fe-9d009c27ab4b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column payment_type = LOOKUPVALUE('gold fct_orders'[payment_method],'gold fct_orders'[order_id],'gold fct_order_items'[order_id])
		lineageTag: 50b1e4ea-043f-41a2-87bd-639c9a1c6ef6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'gold fct_order_items' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "de_portfolio"),
				    gold_fct_order_items = Source{[Schema="gold",Item="fct_order_items"]}[Data],
				    #"Inserted Date" = Table.AddColumn(gold_fct_order_items, "Date", each DateTime.Date([order_purchase_timestamp]), type date)
				in
				    #"Inserted Date"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

