# Shared table metadata for Olist bronze ingestion, bronze_load and the FastAPI service (api/main.py).

TABLE_MAP: dict[str, dict] = {
    "customers": {
        "file": "olist_customers_dataset.csv",
        "columns": [
            "customer_id",
            "customer_unique_id",
            "customer_zip_code_prefix",
            "customer_city",
            "customer_state",
        ],
        "conflict_key": "(customer_id)",
        "hash": False,
    },
    "orders": {
        "file": "olist_orders_dataset.csv",
        "columns": [
            "order_id",
            "customer_id",
            "order_status",
            "order_purchase_timestamp",
            "order_approved_at",
            "order_delivered_carrier_date",
            "order_delivered_customer_date",
            "order_estimated_delivery_date",
        ],
        "conflict_key": "(order_id)",
        "hash": False,
    },
    "order_items": {
        "file": "olist_order_items_dataset.csv",
        "columns": [
            "order_id",
            "order_item_id",
            "product_id",
            "seller_id",
            "shipping_limit_date",
            "price",
            "freight_value",
        ],
        "conflict_key": "(order_id, order_item_id)",
        "hash": False,
    },
    "order_payments": {
        "file": "olist_order_payments_dataset.csv",
        "columns": [
            "order_id",
            "payment_sequential",
            "payment_type",
            "payment_installments",
            "payment_value",
        ],
        "conflict_key": "(order_id, payment_sequential)",
        "hash": False,
    },
    "order_reviews": {
        "file": "olist_order_reviews_dataset.csv",
        "columns": [
            "review_id",
            "order_id",
            "review_score",
            "review_comment_title",
            "review_comment_message",
            "review_creation_date",
            "review_answer_timestamp",
        ],
        "conflict_key": "(review_id, order_id)",
        "hash": False,
    },
    "products": {
        "file": "olist_products_dataset.csv",
        "columns": [
            "product_id",
            "product_category_name",
            "product_name_lenght",
            "product_description_lenght",
            "product_photos_qty",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm",
        ],
        "conflict_key": "(product_id)",
        "hash": False,
    },
    "sellers": {
        "file": "olist_sellers_dataset.csv",
        "columns": [
            "seller_id",
            "seller_zip_code_prefix",
            "seller_city",
            "seller_state",
        ],
        "conflict_key": "(seller_id)",
        "hash": False,
    },
    "geolocation": {
        "file": "olist_geolocation_dataset.csv",
        "columns": [
            "geolocation_zip_code_prefix",
            "geolocation_lat",
            "geolocation_lng",
            "geolocation_city",
            "geolocation_state",
        ],
        "conflict_key": "(_row_hash)",
        "hash": True,
    },
    "product_category_name_translation": {
        "file": "product_category_name_translation.csv",
        "columns": [
            "product_category_name",
            "product_category_name_english",
        ],
        "conflict_key": "(product_category_name)",
        "hash": False,
    },
}